"""baseline

Revision ID: 859fa4fe5bfe
Revises: 
Create Date: 2025-02-10 22:43:59.465971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859fa4fe5bfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 